# -*- coding: utf-8 -*-

import os
from django.core.management.base import BaseCommand, CommandError
from django.conf import settings
from microb.models import Page


class Command(BaseCommand):
    help = 'Build client side routes for Microb'

    def handle(self, *args, **options):
        print "Building client side routes for Microb ..."
        pages = Page.objects.filter(published=True)
        i = 1
        routes = []
        for page in pages:
            url = "/x"+page.url
            val = "page('"+page.url+"', function(ctx, next) { loadPage('"+url+"') } );"
            routes.append(val)
            print str(i)+": "+page.url
            i += 1
        routes_str = '//************ Autogenerated file: do not edit ************\n'+'\n'.join(routes)
        # check directories
        dirpath = settings.BASE_DIR+"/templates/microb"
        if not os.path.isdir(dirpath) is True:
            print "Creating directory templates/microb"
            os.makedirs(dirpath)
        dirpath = settings.BASE_DIR+"/templates/microb/auto"
        if not os.path.isdir(dirpath) is True:
            os.makedirs(dirpath)
            print "Creating directory templates/microb/auto"
        # update
        filepath=settings.BASE_DIR+"/templates/microb/auto/routes.js"
        print "Updating templates/microb/auto/routes.js"
        #~ write the file
        filex = open(filepath, "w")
        filex.write(routes_str)
        filex.close()
        print "OK: "+str(i-1)+" Microb client-side routes built "
        return
